host: 0.0.0.0
port: 8090
log: ./restaurant-api.log
Auth:
  Keyfile: private.pem
  Algrithm:

auth-KeyID: 123
Db:
  Host: localhost
  Port: 5432
  User: postgres
  Password: postgres
  Name: postgres
  DisableTLS: true
  TtsOff: true
